Repository loteque/GoblinGame, pull requests merged in 2024-06, with the labels that each got.

#97 Enemy `Base` spawns in
  project/base/base-temp.png
  project/base/base.gd
  project/base/base.tscn
  project/base/enemy-base-temp.png
  project/example.tscn
  project/tests/test_base.tscn
Labels: Programming

#119 Design enemy patrols
  docs/EnemyPatrol.excalidraw.png
Labels: Design

#146 Changes player and game scale
  project/collectables/scrap/scrap.tscn
  project/new_actor.tscn
  project/player_character.tscn
  project/project.godot
Labels: Programming

#147 Control throw direction with movement
  project/PlayerCharacter.gd
  project/scavange_state.gd
  project/thrown_state.gd
Labels: Programming

#149 Makes goblins only follow when called and gives them a boost
  project/follow_state.gd
  project/goblin_call_area.gd
  project/navigate_state.gd
  project/new_actor.gd
  project/project.godot
  project/tests/test_errors.tscn
Labels: Programming

#150 Add simple grey cave walls to world boundery
  project/main.tscn
  project/static_unit.tscn
Labels: Programming

#148 Loteque/issue88
  project/assets/audio/music/Calm.wav.import
  project/assets/audio/music/Combat.wav.import
  project/assets/audio/music/Exploration.wav.import
  project/assets/audio/music/Lead.wav.import
  project/default_bus_layout.tres
  project/main.tscn
  project/music_manager/MusicManager.gd
  project/static_unit.gd
  project/static_unit.tscn
Labels: Programming, Music

#151 Generate goblins at base
  project/PlayerCharacter.gd
  project/base/CircularProgressBar.gd
  project/base/base.gd
  project/base/base.tscn
  project/base/spawn_progress.gdshader
  project/base/spawner.gd
  project/base_placer.gd
  project/main.tscn
  project/spawner.tscn
  project/src/ui/health_bar.gd
  project/static_unit.tscn
  project/tests/test_base.tscn
Labels: Programming

#152 update actor hurt anim
  project/assets/art/ground_tile_1.png.import
  project/assets/art/ground_tile_2.png.import
  project/assets/art/ground_tile_3.png.import
  project/assets/art/ground_tile_4.png.import
  project/assets/art/poison_river_tiles_enhanced_alt_colors_1.png.import
  project/assets/art/poison_river_tiles_enhanced_alt_colors_2.png.import
  project/assets/art/poison_river_tiles_enhanced_alt_colors_3.png.import
  project/assets/art/poison_river_tiles_enhanced_alt_colors_4.png.import
  project/assets/art/poison_river_tiles_enhanced_frame_1.png.import
  project/assets/art/poison_river_tiles_enhanced_frame_2.png.import
  project/assets/art/spritesheets/615x615_grid.png.import
  project/goblin_0_sprite_frames.tres
  project/new_actor.tscn
Labels: bug, Programming

#154 update attack animation, attack state
  project/attack_state.gd
  project/new_actor.tscn
Labels: bug, Art, Programming

#156 update input map, closes #134
  project/project.godot
Labels: bug, Programming

#159 add lighting
  project/main.tscn
  project/new_actor.tscn
  project/player_character.tscn
  project/src/character/lights/player_character.tres
Labels: enhancement, Art, Programming

#171 add new tiles
  project/main.tscn
Labels: Art, Programming

#174 add sound fx, sfx_manager
  project/PlayerCharacter.gd
  project/base/base.gd
  project/base/base.tscn
  project/collect_state.gd
  project/default_bus_layout.tres
  project/goblin_call_area.gd
  project/new_actor.gd
  project/new_actor.tscn
  project/player_character.tscn
  project/sfx_manager/sfx_manager.gd
  project/sfx_manager/sfx_manager.tscn
  project/src/character/hurt_state.gd
  project/src/character/state/deliver_scrap_state.gd
  project/thrown_state.gd
Labels: Programming, Sfx

#173 Adds health bar to player and death animations
  project/PlayerCharacter.gd
  project/assets/art/spritesheets/sprite-sheet-grid.png
  project/game_manager.gd
  project/goblin_0_sprite_frames.tres
  project/new_actor.gd
  project/new_actor.tscn
  project/player_character.tscn
  project/src/character/ghost.gd
  project/src/character/ghost.gdshader
  project/src/character/ghost.tscn
  project/tests/test_new_actor.tscn
Labels: Programming

#175 add tutorial
  project/PlayerCharacter.gd
  project/assets/audio/music/menuMusic.ogg.import
  project/goblin_call_area.gd
  project/lib/actions_property.gd
  project/main.tscn
  project/player_character.tscn
  project/project.godot
  project/src/character/components/throw_goblin_component.gd
  project/tutorial_manager/TutorialManager.gd
  project/tutorial_manager/message_panel.tscn
Labels: enhancement, Programming

#184 fix actor, player animation issue; closes #177
  project/AnimationController.gd
  project/main.tscn
  project/navigate_state.gd
  project/new_actor.tscn
  project/project.godot
Labels: bug, Programming

#189 Remove unused / failing object references and wrong types.
  project/new_actor.gd
  project/player_character.tscn
  project/scavange_state.gd
  project/src/character/ghost.gd
Labels: bug

#190 add startmenu, pause menu; closes #170
  project/main.tscn
  project/project.godot
  project/src/ui/main_menu.gd
  project/src/ui/main_menu.tscn
Labels: enhancement, Programming

#191 Prevents player from placing next to themselves.
  project/PlayerCharacter.gd
Labels: bug

#194 Allow actors to move around rivers
  project/main.tscn
  project/project.godot
Labels: bug

#193 fix dependency issue with tutorial manager; closes #186
  project/PlayerCharacter.gd
  project/goblin_call_area.gd
  project/src/character/components/throw_goblin_component.gd
  project/tutorial_manager/TutorialManager.gd
Labels: bug

#196 Integrate cave walls assets
  project/background.gdshader
  project/main.tscn
Labels: Programming

#198 add title art and music, closes #197
  project/assets/art/title_screen_complete.png
  project/assets/art/title_screen_complete.png.import
  project/main.tscn
  project/music_manager/MusicManager.gd
  project/src/ui/main_menu.gd
  project/src/ui/main_menu.tscn
Labels: enhancement, Art, Programming, Music

#208 Make dead bodies render behind living
  project/new_actor.gd
Labels: bug

#210 Makes scrap collect more consistent
  project/collect_state.gd
  project/collectables/scrap/scrap.gd
  project/collectables/scrap/scrap.tscn
Labels: bug

#212 map rebalance
  project/main.tscn
  project/new_actor.tscn
  project/player_character.tscn
Labels: enhancement

#224 Show base preview before commiting
  project/PlayerCharacter.gd
  project/base/base.gd
  project/base/base.tscn
  project/base/base_preview.gd
  project/base_placer.gd
  project/player_character.tscn
  project/sfx_manager/sfx_manager.gd
Labels: Programming

#226 Make base green when can place
  project/base/base_preview.gd
Labels: Programming

#227 Refactor TutorialManager out of player (precursor to tutorial scene)
  project/PlayerCharacter.gd
  project/goblin_call_area.gd
  project/main.tscn
  project/src/character/components/throw_goblin_component.gd
  project/tutorial_manager/TutorialManager.gd
Labels: Programming
